
<h1 class="title toc-ignore">DataPracticum1.R</h1>
<h4 class="author"><em>chrisrash</em></h4>
<h4 class="date"><em>Sun Sep 9 10:51:43 2018</em></h4>

</div>


<pre class="r"><code># Set working directory
setwd(&quot;~/Documents/SSOR 690/Data Practicum 1&quot;)

# Read in the raw data
FlightData2007 &lt;- read.csv(&quot;Flight2007a.csv&quot;, header = TRUE, sep = &quot;,&quot;)
FlightData2008 &lt;- read.csv(&quot;Flight2008a.csv&quot;, header = TRUE, sep = &quot;,&quot;)

# Create a data table to reference col names and subset based on row values
library(data.table)
Flights2007 &lt;- data.table(FlightData2007)
Flights2008 &lt;- data.table(FlightData2008)

# Use only Jan through June data
Flights2007c &lt;- Flights2007[Month &lt;= 6]
Flights2008c &lt;- Flights2008[Month &lt;= 6]

# Remove cancelled flights
Flights2007b &lt;- Flights2007c[Cancelled == 0]
Flights2008b &lt;- Flights2008c[Cancelled == 0]

# Subsetting Richmond flights
RVA2007RO &lt;- Flights2007b[Origin == &quot;RIC&quot;]
RVA2007RDa &lt;- Flights2007b[Dest == &quot;RIC&quot;]
RVA2008RO &lt;- Flights2008b[Origin == &quot;RIC&quot;]
RVA2008RDa &lt;- Flights2008b[Dest == &quot;RIC&quot;]

# Remove diverted flights
RVA2007RD &lt;- RVA2007RDa[Diverted == 0]
RVA2008RD &lt;- RVA2008RDa[Diverted == 0]

# Check minimum values
min(RVA2007RD$ArrDelay)</code></pre>
<pre><code>## [1] -42</code></pre>
<pre class="r"><code>min(RVA2007RO$DepDelay)</code></pre>
<pre><code>## [1] -31</code></pre>
<pre class="r"><code>min(RVA2008RD$ArrDelay)</code></pre>
<pre><code>## [1] -46</code></pre>
<pre class="r"><code>min(RVA2008RO$DepDelay)</code></pre>
<pre><code>## [1] -21</code></pre>
<pre class="r"><code># Floor delays to zero
RVA2007RO$DepDelay &lt;- replace(RVA2007RO$DepDelay, RVA2007RO$DepDelay &lt; 0, 0)
RVA2007RD$ArrDelay &lt;- replace(RVA2007RD$ArrDelay, RVA2007RD$ArrDelay &lt; 0, 0)
RVA2008RO$DepDelay &lt;- replace(RVA2008RO$DepDelay, RVA2008RO$DepDelay &lt; 0, 0)
RVA2008RD$ArrDelay &lt;- replace(RVA2008RD$ArrDelay, RVA2008RD$ArrDelay &lt; 0, 0)

# Confirm minimums are zero
min(RVA2007RD$ArrDelay)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>min(RVA2007RO$DepDelay)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>min(RVA2008RD$ArrDelay)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>min(RVA2008RO$DepDelay)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code># Check for NA values
which(is.na(RVA2008RD$ArrDelay))</code></pre>
<pre><code>## integer(0)</code></pre>
<pre class="r"><code>which(is.na(RVA2008RO$DepDelay))</code></pre>
<pre><code>## integer(0)</code></pre>
<pre class="r"><code>which(is.na(RVA2007RD$ArrDelay))</code></pre>
<pre><code>## integer(0)</code></pre>
<pre class="r"><code>which(is.na(RVA2007RO$DepDelay))</code></pre>
<pre><code>## integer(0)</code></pre>
<pre class="r"><code># T-test with full subset
t.test(RVA2007RO$DepDelay, RVA2008RO$DepDelay, conf.level = 0.99)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  RVA2007RO$DepDelay and RVA2008RO$DepDelay
## t = 1.1478, df = 19061, p-value = 0.2511
## alternative hypothesis: true difference in means is not equal to 0
## 99 percent confidence interval:
##  -0.8229239  2.1455236
## sample estimates:
## mean of x mean of y 
##  14.64294  13.98164</code></pre>
<pre class="r"><code>t.test(RVA2007RD$ArrDelay, RVA2008RD$ArrDelay, conf.level = 0.99)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  RVA2007RD$ArrDelay and RVA2008RD$ArrDelay
## t = 3.6453, df = 19102, p-value = 0.0002678
## alternative hypothesis: true difference in means is not equal to 0
## 99 percent confidence interval:
##  0.590023 3.433178
## sample estimates:
## mean of x mean of y 
##  19.15897  17.14737</code></pre>
<pre class="r"><code># Generate random sample
RVA2007ROSample &lt;- RVA2007RO[sample(nrow(RVA2007RO), 1000, replace = FALSE, prob = NULL),]
RVA2008ROSample &lt;- RVA2008RO[sample(nrow(RVA2008RO), 1000, replace = FALSE, prob = NULL),]
RVA2007RDSample &lt;- RVA2007RD[sample(nrow(RVA2007RD), 1000, replace = FALSE, prob = NULL),]
RVA2008RDSample &lt;- RVA2008RD[sample(nrow(RVA2008RD), 1000, replace = FALSE, prob = NULL),]

# T-test with sample
t.test(RVA2007ROSample$DepDelay, RVA2008ROSample$DepDelay, conf.level = 0.99)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  RVA2007ROSample$DepDelay and RVA2008ROSample$DepDelay
## t = 0.78063, df = 1997.7, p-value = 0.4351
## alternative hypothesis: true difference in means is not equal to 0
## 99 percent confidence interval:
##  -3.115755  5.821755
## sample estimates:
## mean of x mean of y 
##    15.232    13.879</code></pre>
<pre class="r"><code>t.test(RVA2007RDSample$ArrDelay, RVA2008RDSample$ArrDelay, conf.level = 0.99)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  RVA2007RDSample$ArrDelay and RVA2008RDSample$ArrDelay
## t = 1.6165, df = 1995.3, p-value = 0.1061
## alternative hypothesis: true difference in means is not equal to 0
## 99 percent confidence interval:
##  -1.580907  6.894907
## sample estimates:
## mean of x mean of y 
##    19.078    16.421</code></pre>
<pre class="r"><code># Create factor for Delay
RVA2007RO$Carr &lt;- ifelse(RVA2007RO$DepDelay &gt; 0, 1, 0)
RVA2007RD$Carr &lt;- ifelse(RVA2007RD$ArrDelay &gt; 0, 1, 0)
RVA2008RO$Carr &lt;- ifelse(RVA2008RO$DepDelay &gt; 0, 1, 0)
RVA2008RD$Carr &lt;- ifelse(RVA2008RD$ArrDelay &gt; 0, 1, 0)

# Use glm function for logistic regression
mylogitRVA2007RO &lt;- glm(Carr ~ UniqueCarrier, data = RVA2007RO, family = &quot;binomial&quot;)
mylogitRVA2007RD &lt;- glm(Carr ~ UniqueCarrier, data = RVA2007RD, family = &quot;binomial&quot;)
mylogitRVA2008RO &lt;- glm(Carr ~ UniqueCarrier, data = RVA2008RO, family = &quot;binomial&quot;)
mylogitRVA2008RD &lt;- glm(Carr ~ UniqueCarrier, data = RVA2008RD, family = &quot;binomial&quot;)

# Use summary function to view results of logisitic regression
# Wald test shows overall significance of Unique Carrier column
library(aod)
summary(mylogitRVA2007RO)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Carr ~ UniqueCarrier, family = &quot;binomial&quot;, data = RVA2007RO)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.2357  -0.9727  -0.8655   1.3309   1.7746  
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -0.65360    0.07877  -8.298  &lt; 2e-16 ***
## UniqueCarrierAA  0.29976    0.11930   2.513  0.01198 *  
## UniqueCarrierB6  0.14716    0.10589   1.390  0.16462    
## UniqueCarrierDL -0.13044    0.10604  -1.230  0.21865    
## UniqueCarrierEV  0.63921    0.14351   4.454 8.42e-06 ***
## UniqueCarrierFL -0.68886    0.11130  -6.189 6.04e-10 ***
## UniqueCarrierMQ  0.78964    0.10445   7.560 4.04e-14 ***
## UniqueCarrierNW  0.33269    0.22987   1.447  0.14781    
## UniqueCarrierOH -0.13540    0.10282  -1.317  0.18787    
## UniqueCarrierUA  0.32011    0.13463   2.378  0.01742 *  
## UniqueCarrierUS  0.32356    0.10823   2.990  0.00279 ** 
## UniqueCarrierXE  0.15103    0.09299   1.624  0.10436    
## UniqueCarrierYV  0.11379    0.14739   0.772  0.44010    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 12343  on 9384  degrees of freedom
## Residual deviance: 12061  on 9372  degrees of freedom
## AIC: 12087
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>wald.test(b = coef(mylogitRVA2007RO), Sigma = vcov(mylogitRVA2007RO), Terms = 2:13)</code></pre>
<pre><code>## Wald test:
## ----------
## 
## Chi-squared test:
## X2 = 265.8, df = 12, P(&gt; X2) = 0.0</code></pre>
<pre class="r"><code>summary(mylogitRVA2007RD)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Carr ~ UniqueCarrier, family = &quot;binomial&quot;, data = RVA2007RD)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.658  -1.224   0.861   1.116   1.440  
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -0.59901    0.07780  -7.700 1.36e-14 ***
## UniqueCarrierAA  0.94150    0.11866   7.934 2.12e-15 ***
## UniqueCarrierB6  0.74515    0.10384   7.176 7.19e-13 ***
## UniqueCarrierDL  0.60551    0.10191   5.942 2.82e-09 ***
## UniqueCarrierEV  0.09011    0.14645   0.615    0.538    
## UniqueCarrierFL  0.09685    0.10188   0.951    0.342    
## UniqueCarrierMQ  0.98698    0.10442   9.452  &lt; 2e-16 ***
## UniqueCarrierNW  1.68235    0.25863   6.505 7.78e-11 ***
## UniqueCarrierOH  1.08056    0.10004  10.801  &lt; 2e-16 ***
## UniqueCarrierUA  0.55819    0.13311   4.193 2.75e-05 ***
## UniqueCarrierUS  1.40031    0.11089  12.628  &lt; 2e-16 ***
## UniqueCarrierXE  0.70679    0.09138   7.735 1.04e-14 ***
## UniqueCarrierYV  0.75092    0.14344   5.235 1.65e-07 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 13003  on 9397  degrees of freedom
## Residual deviance: 12637  on 9385  degrees of freedom
## AIC: 12663
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>wald.test(b = coef(mylogitRVA2007RD), Sigma = vcov(mylogitRVA2007RD), Terms = 2:13)</code></pre>
<pre><code>## Wald test:
## ----------
## 
## Chi-squared test:
## X2 = 348.9, df = 12, P(&gt; X2) = 0.0</code></pre>
<pre class="r"><code>summary(mylogitRVA2008RO)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Carr ~ UniqueCarrier, family = &quot;binomial&quot;, data = RVA2008RO)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.1488  -0.8701  -0.8485   1.4664   1.8349  
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)      -0.77632    0.07047 -11.016  &lt; 2e-16 ***
## UniqueCarrierAA  -0.01097    0.11931  -0.092  0.92671    
## UniqueCarrierB6  -0.06003    0.09755  -0.615  0.53832    
## UniqueCarrierDL  -0.01826    0.10066  -0.181  0.85605    
## UniqueCarrierEV   0.63817    0.12192   5.234 1.66e-07 ***
## UniqueCarrierFL  -0.26770    0.10175  -2.631  0.00851 ** 
## UniqueCarrierMQ   0.62427    0.10207   6.116 9.58e-10 ***
## UniqueCarrierOH  -0.03274    0.09489  -0.345  0.73005    
## UniqueCarrierOO  11.34235  119.46806   0.095  0.92436    
## UniqueCarrierUA   0.70861    0.13148   5.389 7.07e-08 ***
## UniqueCarrierUS  -0.70165    0.11775  -5.959 2.54e-09 ***
## UniqueCarrierXE   0.11860    0.08685   1.366  0.17208    
## UniqueCarrierYV  -0.43477    0.15332  -2.836  0.00457 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 12255  on 9749  degrees of freedom
## Residual deviance: 12012  on 9737  degrees of freedom
## AIC: 12038
## 
## Number of Fisher Scoring iterations: 9</code></pre>
<pre class="r"><code>wald.test(b = coef(mylogitRVA2008RO), Sigma = vcov(mylogitRVA2008RO), Terms = 2:13)</code></pre>
<pre><code>## Wald test:
## ----------
## 
## Chi-squared test:
## X2 = 233.5, df = 12, P(&gt; X2) = 0.0</code></pre>
<pre class="r"><code>summary(mylogitRVA2008RD)</code></pre>
<pre><code>## 
## Call:
## glm(formula = Carr ~ UniqueCarrier, family = &quot;binomial&quot;, data = RVA2008RD)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.2807  -1.1094  -0.9346   1.1774   1.4414  
## 
## Coefficients:
##                 Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -0.37013    0.06635  -5.578 2.43e-08 ***
## UniqueCarrierAA  0.38210    0.11130   3.433 0.000597 ***
## UniqueCarrierB6  0.08244    0.09120   0.904 0.366010    
## UniqueCarrierDL  0.20809    0.09414   2.211 0.027069 *  
## UniqueCarrierEV -0.14993    0.12232  -1.226 0.220309    
## UniqueCarrierFL  0.13200    0.09284   1.422 0.155099    
## UniqueCarrierMQ  0.44844    0.09904   4.528 5.96e-06 ***
## UniqueCarrierOH  0.51135    0.08889   5.753 8.79e-09 ***
## UniqueCarrierUA  0.60980    0.12966   4.703 2.56e-06 ***
## UniqueCarrierUS -0.23187    0.10132  -2.289 0.022106 *  
## UniqueCarrierXE  0.37013    0.08196   4.516 6.30e-06 ***
## UniqueCarrierYV -0.08186    0.13474  -0.608 0.543482    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 13461  on 9750  degrees of freedom
## Residual deviance: 13327  on 9739  degrees of freedom
## AIC: 13351
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>wald.test(b = coef(mylogitRVA2008RD), Sigma = vcov(mylogitRVA2008RD), Terms = 2:12)</code></pre>
<pre><code>## Wald test:
## ----------
## 
## Chi-squared test:
## X2 = 131.3, df = 11, P(&gt; X2) = 0.0</code></pre>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
